name: "CD: Terraform Apply (Dev Environment)"

on:
  push:
    branches:
      - dev
    paths:
      - "terraform/**"

jobs:
  apply:
    name: "Terragrunt Apply on Dev"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Terragrunt
        uses: gruntwork-io/setup-terragrunt@v1

      - name: Run Terragrunt Apply for all Dev Segments
        run: |
          make tg-foundation-dev-apply-all --terragrunt-non-interactive
          make tg-application-dev-apply-all --terragrunt-non-interactive
          make tg-data_processing-dev-apply-all --terragrunt-non-interactive